### ISSUE TITLE
aws-ebs-csi-driver doesn't create a role in EKS

### ISSUE THREAD

**Issue by mhernahapetyan** [aws-ia/terraform-aws-eks-blueprints-addons#252]
module "eks_blueprints_kubernetes_addons" {
  source = "aws-ia/eks-blueprints-addons/aws"
  version = "1.6.0"

  cluster_name      = module.eks_blueprints.eks_cluster_id
  cluster_endpoint  = module.eks_blueprints.eks_cluster_endpoint
  cluster_version   = module.eks_blueprints.eks_cluster_version
  oidc_provider_arn = module.eks_blueprints.eks_oidc_provider_arn

  eks_addons = {
    aws-ebs-csi-driver = {
      most_recent = true
    }
    coredns = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
    kubecost_kubecost = {
      most_recent = true
    }
  }
  
  I don't see any irsa role created for aws-ebs-csi-driver, does someone have the same issue?

**Comment by patrickmukumbu** [comment]
I faced the same issue. I had to create it separately

**Comment by bryantbiggs** [comment]
EKS addons do not create IRSA since it uses a generic interface (users can pass any supported EKS addon into `eks_addons`). You will need to supply the IRSA role arn as part of the input as shown here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/bf37e2fefa3317e9758e57cbdd139b79aba065e0/tests/complete/main.tf#L112 for those EKS addons that support IRSA

**Comment by Almenon** [comment]
Just ran into the same issue. Your answer fixed it, thanks! 

The example in this repo's readme uses the EBS CSI driver but does not supply the ISRA role arn, so the example should be adjusted, right?

It would also be good to note this in the v4 to v5 upgrade notes, as this is a departure from v4 behavior.

**Comment by danpilch** [comment]
yet another thing _not_ in the migration guide that has caused problems!
